version: "3"

services:
    mysql:
        build: mysql
        domainname: siffra.local
        hostname: mysql
        privileged: true
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    postgres:
        build: postgres
        domainname: siffra.local
        hostname: postgres
        privileged: true
        environment: 
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWD=laravel@1
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        build: redis
        domainname: siffra.local
        hostname: redis
        privileged: true
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    redis-data:
    postgres-data:
    mysql-data: