version: "3"

services:
    mysql:
        build: mysql
        container_name: "mysql"
        domainname: siffra.local
        image: lbenevenuto/mysql
        hostname: mysql
        privileged: true
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    postgres:
        build: postgres
        container_name: "postgres"
        domainname: siffra.local
        hostname: postgres
        privileged: true
        environment: 
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWD=laravel@1
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        build: redis
        container_name: "redis"
        domainname: siffra.local
        hostname: redis
        privileged: true
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
    pgadmin:
        build: pgadmin
        container_name: "pgadmin"
        domainname: siffra.local
        hostname: pgadmin
        privileged: true
        environment: 
            - PGADMIN_DEFAULT_EMAIL=luiz@siffra.com.br
            - PGADMIN_DEFAULT_PASSWORD=123
        ports: 
            - "8080:80"
        volumes: 
            - pgadmin-data:/var/lib/pgadmin
        depends_on: 
            - postgres
    portainer:
        build: portainer
        container_name: "portainer-app"
        domainname: siffra.local
        #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
        command: --host=unix:///var/run/docker.sock
        ports: 
        - "9000:9000"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

    watchtower:
        build: watchtower
        container_name: "portainer-watchtower"
        domainname: siffra.local
        command: --cleanup portainer-app portainer-watchtower --interval 30 --debug
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
    redis-data:
    postgres-data:
    mysql-data:
    pgadmin-data:
    portainer_data: