version: "3"

services:
    mysql:
        build: mysql
        container_name: "mysql"
        domainname: siffra.local
        hostname: mysql
        privileged: true
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
    postgres:
        build: postgres
        container_name: "postgres"
        domainname: siffra.local
        hostname: postgres
        privileged: true
        environment: 
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWD=laravel@1
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    redis:
        build: redis
        #image: redis:alpine
        container_name: "redis"
        domainname: siffra.local
        hostname: redis
        privileged: true
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
    pgadmin:
        build: pgadmin
        container_name: "pgadmin"
        domainname: siffra.local
        hostname: pgadmin
        privileged: true
        environment: 
            - PGADMIN_DEFAULT_EMAIL=luiz@siffra.com.br
            - PGADMIN_DEFAULT_PASSWORD=123
        ports: 
            - "8080:80"
        volumes: 
            - pgadmin-data:/var/lib/pgadmin
        depends_on: 
            - postgres
    phpmyadmin:
        build: phpmyadmin
        container_name: phpmyadmin
        domainname: siffra.local
        environment:
            - PMA_ARBITRARY=0
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=123456
        restart: always
        ports:
            - 8081:80
        volumes:
            - phpmyadmin-data:/sessions
    adminer:
        build: adminer
        container_name: adminer
        domainname: siffra.local
        restart: always
        ports:
            - 8082:8080
    portainer:
        build: portainer
        container_name: "portainer"
        domainname: siffra.local
        #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
        command: --host=unix:///var/run/docker.sock
        ports: 
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data

    # watchtower:
    #     build: watchtower
    #     container_name: "watchtower"
    #     domainname: siffra.local
    #     command: --interval 30 --cleanup --debug
    #     volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock
    #     - ~/.docker/config.json:/config.json

volumes:
    redis-data:
    postgres-data:
    mysql-data:
    pgadmin-data:
    phpmyadmin-data:
    portainer-data:
    adminer-data: